#!/usr/bin/env Rscript

# set our preferred CRAN repo (for this project)
r <- getOption("repos")
r["CRAN"] <- "https://cran.rstudio.com"
options(repos = r)

# Create a list of required packages
required.packages <- c("testthat", "magrittr")

# Figure out which ones are not already installed
to.install <- required.packages[!(required.packages %in% installed.packages()[, "Package"])]

# Install the missing packages if necessary
if (length(to.install)) install.packages(to.install)

# Load required packages
lapply(required.packages, require, character.only = TRUE)

# enable color output (maybe only needed for Windows?)
options(crayon.enabled=TRUE)

# Utility function to "clear" the screen (actually prints 100 newlines)
clear <- function() system2("clear")

# Callback to run tests in changed directories
# parameters are required, even if unused
run.tests.on.changed <- function(added, deleted, modified) {
  # Clear the screen
  clear()
  # run the tests in this directory
  test_dir('.')
  # return true so that watch() won't exit
  return(TRUE)
}

# Clear the screen
clear()

# Run the tests the first time
test_dir('.')

# Watch all problem solution directories for changes to source code files
watch('.', run.tests.on.changed, pattern = ".*\\.R")

# CAUTION: Nothing will run AFTER `watch()` has been called